### ISSUE TITLE
AccessLogTestCase.test_log_data_truncated fails with axes.models.AccessAttempt.DoesNotExist: AccessAttempt matching query does not exist

### ISSUE THREAD

**Issue by jayvdb** [jazzband/django-axes#1012]
On openSUSE Tumbleweed builds, I am seeing the following error with v5.40.1.  Has it already been fixed?
```
[   82s] =================================== FAILURES ===================================
[   82s] __________________ AccessLogTestCase.test_log_data_truncated ___________________
[   82s] 
[   82s] self = <tests.test_logging.AccessLogTestCase testMethod=test_log_data_truncated>
[   82s] 
[   82s]     def test_log_data_truncated(self):
[   82s]         """
[   82s]         Test that get_query_str properly truncates data to the max_length (default 1024).
[   82s]         """
[   82s]     
[   82s]         # An impossibly large post dict
[   82s]         extra_data = {"a" * x: x for x in range(1024)}
[   82s]         self.login(**extra_data)
[   82s] >       self.assertEqual(len(AccessAttempt.objects.latest("id").post_data), 1024)
[   82s] 
[   82s] tests/test_logging.py:80: 
[   82s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   82s] /usr/lib/python3.8/site-packages/django/db/models/manager.py:85: in manager_method
[   82s]     return getattr(self.get_queryset(), name)(*args, **kwargs)
[   82s] /usr/lib/python3.8/site-packages/django/db/models/query.py:1040: in latest
[   82s]     return self.reverse()._earliest(*fields)
[   82s] /usr/lib/python3.8/site-packages/django/db/models/query.py:1023: in _earliest
[   82s]     return obj.get()
[   82s] _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
[   82s] 
[   82s] self = <QuerySet []>, args = (), kwargs = {}, clone = <QuerySet []>, limit = 21
[   82s] num = 0
[   82s] 
[   82s]     def get(self, *args, **kwargs):
[   82s]         """
[   82s]         Perform the query and return a single object matching the given
[   82s]         keyword arguments.
[   82s]         """
[   82s]         if self.query.combinator and (args or kwargs):
[   82s]             raise NotSupportedError(
[   82s]                 "Calling QuerySet.get(...) with filters after %s() is not "
[   82s]                 "supported." % self.query.combinator
[   82s]             )
[   82s]         clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
[   82s]         if self.query.can_filter() and not self.query.distinct_fields:
[   82s]             clone = clone.order_by()
[   82s]         limit = None
[   82s]         if (
[   82s]             not clone.query.select_for_update
[   82s]             or connections[clone.db].features.supports_select_for_update_with_limit
[   82s]         ):
[   82s]             limit = MAX_GET_RESULTS
[   82s]             clone.query.set_limits(high=limit)
[   82s]         num = len(clone)
[   82s]         if num == 1:
[   82s]             return clone._result_cache[0]
[   82s]         if not num:
[   82s] >           raise self.model.DoesNotExist(
[   82s]                 "%s matching query does not exist." % self.model._meta.object_name
[   82s]             )
[   82s] E           axes.models.AccessAttempt.DoesNotExist: AccessAttempt matching query does not exist.
[   82s] 
[   82s] /usr/lib/python3.8/site-packages/django/db/models/query.py:650: DoesNotExist
[   82s] ------------------------------ Captured log call -------------------------------
[   82s] ERROR    django.security.TooManyFieldsSent:exception.py:125 The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
[   82s] Traceback (most recent call last):
[   82s]   File "/usr/lib/python3.8/site-packages/django/core/handlers/exception.py", line 56, in inner
[   82s]     response = get_response(request)
[   82s]   File "/usr/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
[   82s]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[   82s]   File "/usr/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
[   82s]     return bound_method(*args, **kwargs)
[   82s]   File "/usr/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
[   82s]     response = view_func(request, *args, **kwargs)
[   82s]   File "/usr/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 430, in login
[   82s]     and REDIRECT_FIELD_NAME not in request.POST
[   82s]   File "/usr/lib/python3.8/site-packages/django/core/handlers/wsgi.py", line 100, in _get_post
[   82s]     self._load_post_and_files()
[   82s]   File "/usr/lib/python3.8/site-packages/django/http/request.py", line 373, in _load_post_and_files
[   82s]     self._post, self._files = self.parse_file_upload(self.META, data)
[   82s]   File "/usr/lib/python3.8/site-packages/django/http/request.py", line 323, in parse_file_upload
[   82s]     return parser.parse()
[   82s]   File "/usr/lib/python3.8/site-packages/django/http/multipartparser.py", line 123, in parse
[   82s]     return self._parse()
[   82s]   File "/usr/lib/python3.8/site-packages/django/http/multipartparser.py", line 203, in _parse
[   82s]     raise TooManyFieldsSent(
[   82s] django.core.exceptions.TooManyFieldsSent: The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.
[   82s] WARNING  django.request:log.py:241 Bad Request: /admin/login/
```

**Comment by aleksihakli** [comment]
Seems like [`settings.DATA_UPLOAD_MAX_NUMBER_FIELDS`](https://docs.djangoproject.com/en/4.1/ref/settings/#data-upload-max-number-fields) needs to be configured higher for this test to work, or alternatively the number of fields in the test lowered. Anyone interested in updating the implementation?
