### ISSUE TITLE
django-axes==5.40.1 , Running Django tests now cause  "AttributeError: 'WSGIRequest' object has no attribute 'axes_ip_address'"

### ISSUE THREAD

**Issue by rmincling** [jazzband/django-axes#1020]
Hi,

We have recently updated this package as well as Django to 4.1.7  (Python 3.9)  but we seem to be seeing these errors when running our Django tests (which worked with previous versions). We disable axes as recommended (see below). We were wondering if there are extra steps we're now missing when trying to disable axes when running the tests.

**Packages involved**
```
channels==4.0.0
Django==4.1.7
django-axes==5.40.1
django-ipware==5.0.0
djangorestframework==3.14.0
requests==2.28.2
```

**Django settings for tests:**
```
AXES_HANDLER = 'axes.handlers.dummy.AxesDummyHandler'
ATOMIC_REQUESTS = False
AXES_ENABLED = False
AXES_LOCK_OUT_AT_FAILURE = False
AXES_ONLY_USER_FAILURES = False
```

**The error traceback:**
```
Traceback (most recent call last):
  File "/Users/robertm/dev/platform/d3_platform/src/platform_v2/site_setup/tests/test_rest_api.py", line 515, in test_update_settings
    self.login(self.client, self.primary_project_users[self.user_constants.ADMIN], data={'project': self.primary_project.id})
  File "/Users/robertm/dev/platform/d3_platform/src/platform_v2/core/tests/tests.py", line 123, in login
    return client.post(reverse('rest_login'), valid_login_data, **header, format='json')
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/test.py", line 296, in post
    response = super().post(
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/test.py", line 210, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/test.py", line 234, in generic
    return super().generic(
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/test/client.py", line 541, in generic
    return self.request(**r)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/test.py", line 286, in request
    return super().request(**kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/test.py", line 238, in request
    request = super().request(**kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/test/client.py", line 810, in request
    self.check_exception(response)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/test/client.py", line 663, in check_exception
    raise exc_value
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/sentry_sdk/integrations/django/views.py", line 85, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/src/platform_v2/core/views.py", line 23, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/dj_rest_auth/views.py", line 48, in dispatch
    return super().dispatch(*args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/robertm/dev/platform/d3_platform/src/platform_v2/accounts/rest_api/views.py", line 1143, in post
    self.login()
  File "/Users/robertm/dev/platform/d3_platform/src/platform_v2/accounts/rest_api/views.py", line 1059, in login
    reset_user_attempts(self.request, credentials)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/axes/attempts.py", line 98, in reset_user_attempts
    attempts_list = filter_user_attempts(request, credentials)
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/axes/attempts.py", line 41, in filter_user_attempts
    username, request.axes_ip_address, request.axes_user_agent
  File "/Users/robertm/dev/platform/d3_platform/lib/python3.9/site-packages/rest_framework/request.py", line 418, in __getattr__
    return self.__getattribute__(attr)
AttributeError: 'Request' object has no attribute 'axes_ip_address'
```

Any advice would be much appreciated

**Comment by aleksihakli** [comment]
Hey @rmincling!

One option you'd have is to just remove `axes` from `INSTALLED_APPS` for your test settings, which would probably be the easiest option for running the tests, if your web site works correctly with the settings.

Another is to take a closer look at the error.

The IP address is calculated in the `axes.proxy.AxesProxyHandler.update_request` method:

https://github.com/jazzband/django-axes/blob/e56f4c92716f79250ab526c800cd598cd51dcfff/axes/handlers/proxy.py#L92

The calculation is done, by default, with the `django-ipware` package `ipware.ip.get_client_ip` method:

https://github.com/jazzband/django-axes/blob/e56f4c92716f79250ab526c800cd598cd51dcfff/axes/helpers.py#L151

But it can also be overridden with the `AXES_CLIENT_IP_CALLABLE` setting, so you could implement a function, lambda, or a callable for resolving the IP from the Django REST Framework HTTP request object as well.

Btw did you try Axes with the newest version of Django (i.e. 4.1.8 or 4.2.1) and DRF yet? Probably won't affect the result but could be good to check since upgrading the version should be a rather minimal thing to test.
