### ISSUE TITLE
Import Error in 2.3.0

### ISSUE THREAD

**Issue by WillCallahan** [jazzband/django-axes#204]
Using the Python 2.7.11, Django Axes attempts to import inet_pton which does not exist.

```
"C:\Program Files (x86)\JetBrains\PyCharm 2016.2.1\bin\runnerw.exe" C:\Python27\python.exe "C:/SomeHiddenPath/manage.py" runserver 8000
Unhandled exception in thread started by <function wrapper at 0x042097B0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 115, in populate
    app_config.ready()
  File "C:\Python27\lib\site-packages\axes\apps.py", line 9, in ready
    from axes.decorators import watch_login
  File "C:\Python27\lib\site-packages\axes\decorators.py", line 3, in <module>
    from socket import inet_pton, AF_INET6
ImportError: cannot import name inet_pton
```

**Comment by camilonova** [comment]
I just tried to import the package on python 2.7.10 and it works.

Please check if your Python installation is complete.

**Comment by fesoliveira014** [comment]
Just tried this under Windows and got the same problem. Solved this by using `win_inet_pton` instead:

`form win_inet_pton import inet_pton`

I recommend a clause to check if axes is being run under windows, and import this accordingly.

**Comment by fesoliveira014** [comment]
As described on the [Python documentation](https://docs.python.org/2/library/socket.html#socket.inet_pton), `inet_pton` is only available under certain Unix distribuitions.

**Comment by manishReddevil** [comment]
`from win_inet_pton import inet_pton` did the trick.
I kept it in settings.py and the error was gone

**Comment by hsiaoyi0504** [comment]
@camilonova  I think this issue should be re-open. I can confirm this issue, and the trick `from win_inet_pton import inet_pton` work, but it still need to be fixed.
