### ISSUE TITLE
Problem with inet_pton

### ISSUE THREAD

**Issue by RodolpheStratX** [jazzband/django-axes#208]
Hello,

I've just installed `django-axes` and ran `python manage.py migrate` only to get this error:
```
Traceback (most recent call last):
  File "src\manage.py", line 10, in <module> execute_from_command_line(sys.argv)
  File "C:\Users\rbreton\Programmation\ibd-via\venv\lib\site-packages\django\core\management\__init__.py", line 353, in execute _utility.execute()
  File "C:\Users\rbreton\Programmation\ibd-via\venv\lib\site-packages\django\core\management\__init__.py", line 327, in execute django.setup()
  File "C:\Users\rbreton\Programmation\ibd-via\venv\lib\site-packages\django\__init__.py", line 18, in setup apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\rbreton\Programmation\ibd-via\venv\lib\site-packages\django\apps\registry.py", line 115, in populate app_config.ready()
  File "C:\Users\rbreton\Programmation\ibd-via\venv\lib\site-packages\axes\apps.py", line 9, in ready from axes.decorators import watch_login
  File "C:\Users\rbreton\Programmation\ibd-via\venv\lib\site-packages\axes\decorators.py", line 3, in <module> from socket import inet_pton, AF_INET6, error
ImportError: cannot import name inet_pton
```

After some googling, I found that `inet_pton` exists in `socket` only in Python 3.x.
In Python 2.7, it seems it's named `inet_aton` and I'm using Python 2.7 and cannot migrate to 3.x.

How can I make it work?

**Comment by RodolpheStratX** [comment]
More information.

inet_pton exists in socket in v2.7 and v3.x.
It's just that it's missing on Windows in v2.7...

Could you check the os/platform before the import?

**Comment by odedhar** [comment]
You can use https://github.com/hickeroar/win_inet_pton - just follow the example

**Comment by RodolpheStratX** [comment]
I already tried installing {{win_inet_pton}} but I might have missed something because that didn't help.
I'll give it another shot, then.

Thank you for answering!

**Comment by RobertGilmour** [comment]
*For anyone who comes across this in the future*

I got this working by installing win_inet_pton
using ```pip install win_inet_pton```

then at the top of my **settings.py** under import os entered:
```import win_inet_pton```
