### ISSUE TITLE
Support for Django 2.0

### ISSUE THREAD

**Issue by jvalleroy** [jazzband/django-axes#255]
Although Django 2.0 is not released yet, it is coming in a few weeks, and hopefully we can be ready to support it.

With Django 2.0 beta, this test is failing:
```
  ======================================================================
  ERROR: tests (unittest.loader._FailedTest)
  ----------------------------------------------------------------------
  ImportError: Failed to import test module: tests
  Traceback (most recent call last):
    File "/usr/lib/python3.6/unittest/loader.py", line 153, in loadTestsFromName
      module = __import__(module_name)
    File "«BUILDDIR»/axes/tests.py", line 13, in <module>
      from django.core.urlresolvers import NoReverseMatch
  ModuleNotFoundError: No module named 'django.core.urlresolvers'
```
Reported at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=880833.

**Comment by camilonova** [comment]
We are working on a non backwards version. I'll leave this open until we publish that one.

**Comment by camilonova** [comment]
This is fixed at the new version.
