### ISSUE TITLE
readthedocs needs updating

### ISSUE THREAD

**Issue by eschercode** [jazzband/django-axes#285]
Public documentation [here](https://django-axes.readthedocs.io/en/latest/#) is still stuck at version 2.2

**Comment by jezdez** [comment]
This is the traceback I see in the build output:

```
Collecting Django (from -r /home/docs/checkouts/readthedocs.org/user_builds/django-axes/checkouts/stable/requirements.txt (line 1))
  Using cached Django-2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-MfBMQI/Django/setup.py", line 32, in <module>
        version = __import__('django').get_version()
      File "django/__init__.py", line 1, in <module>
        from django.utils.version import get_version
      File "django/utils/version.py", line 61, in <module>
        @functools.lru_cache()
    AttributeError: 'module' object has no attribute 'lru_cache'
```

This basically means it tries to install Django 2.0 (since the version of Django isn't pinned in setup.py) and fails because the RTD project was running on Python 2.x.

I've switched just switched the project on RTD to Python 3.x and the build passed.
