### ISSUE TITLE
No module named 'axes.backends'

### ISSUE THREAD

**Issue by HmzAli** [jazzband/django-axes#356]
I've followed the installation instruction in the docs but keep getting the error above after running `python manage.py runserver`.

I'm using version 2.3.3, which should be compatible with my versions of django (1.9.13) and python (3.4).

Here is my auth settings:
```
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesModelBackend',
    'django.contrib.auth.backends.ModelBackend',
    'devices.authentication.TokenAuthBackend',
    'boost.authentication.UnsafeCookieBackend',
]
```

And apps settings:

```
EXTERNAL_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.admin',
    'django.contrib.humanize',
    'axes',
)```
 
Full stack trace:
```Internal Server Error: /admin/login/
 Traceback (most recent call last):
   File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 149, in get_response
     response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py", line 147, in get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
   File "/usr/local/lib/python3.4/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
     response = view_func(request, *args, **kwargs)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 398, in login
     context = dict(self.each_context(request),
   File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 315, in each_context
     'available_apps': self.get_app_list(request),
   File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 488, in get_app_list
     app_dict = self._build_app_dict(request)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/sites.py", line 434, in _build_app_dict
     has_module_perms = model_admin.has_module_permission(request)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/admin/options.py", line 474, in has_module_permission
     return request.user.has_module_perms(self.opts.app_label)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/models.py", line 439, in has_module_perms
     return _user_has_module_perms(self, module)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/models.py", line 196, in _user_has_module_perms
     for backend in auth.get_backends():
   File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 38, in get_backends
     return _get_backends(return_tuples=False)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 27, in _get_backends
     backend = load_backend(backend_path)
   File "/usr/local/lib/python3.4/site-packages/django/contrib/auth/__init__.py", line 21, in load_backend
     return import_string(path)()
   File "/usr/local/lib/python3.4/site-packages/django/utils/module_loading.py", line 20, in import_string
     module = import_module(module_path)
   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
     return _bootstrap._gcd_import(name[level:], package, level)
   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
   File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
 ImportError: No module named 'axes.backends'
```

**Comment by markddavidoff** [comment]
did you run `python manage.py migrate`?

**Comment by markddavidoff** [comment]
Also, version 2.3.3 is and used another way of interfacing with axes than what is in the current instructions. You can either look at the instructions that came with the old version or upgrade to 4.3+.

**Comment by markddavidoff** [comment]
Closing issue as this is in regards to an old version if you experience this issue after upgrade, please open another issue
