### ISSUE TITLE
ImportError: cannot import name 'LoginView'

### ISSUE THREAD

**Issue by HmzAli** [jazzband/django-axes#360]
Getting this error when running any `python manage.py` command. 

Using version 4.0.0 with Python (3.4.7) and Django (1.9.13).

Stack trace:
```Traceback (most recent call last):
  File "manage.py", line 6, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/usr/local/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/usr/local/lib/python3.4/site-packages/axes/apps.py", line 8, in ready
    from django.contrib.auth.views import LoginView
ImportError: cannot import name 'LoginView'```

Thanks!

**Comment by markddavidoff** [comment]
Hi! Can you try the most recent version please and let me know if you're still seeing this error?

**Comment by HmzAli** [comment]
Upgraded to 4.4.0. Still getting the error.

**Comment by camilonova** [comment]
Which django version are you using?

**Comment by camilonova** [comment]
The lowest supported django version is 1.11
