### ISSUE TITLE
Module "axes.backends" does not define a "AxesBackend" 

### ISSUE THREAD

**Issue by drozdowsky** [jazzband/django-axes#484]
Related to: https://github.com/jazzband/django-axes/issues/356
Version: 4.5.4 and 3.0.3
I have configured my project like in the *Installation Notes*
I get this error when I try to access /admin page

`Traceback (most recent call last):
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
    response = self._middleware_chain(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/deprecation.py", line 140, in __call__
    response = self.get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
    response = response_for_exception(request, exc)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/home/self/work/rp/reporting/src/reporting/wsgi.py", line 24, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/views/decorators/cache.py", line 57, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 377, in login
    self.each_context(request),
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 297, in each_context
    'available_apps': self.get_app_list(request),
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 465, in get_app_list
    app_dict = self._build_app_dict(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 413, in _build_app_dict
    has_module_perms = model_admin.has_module_permission(request)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/admin/options.py", line 483, in has_module_permission
    return request.user.has_module_perms(self.opts.app_label)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/auth/models.py", line 442, in has_module_perms
    return _user_has_module_perms(self, module)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/auth/models.py", line 201, in _user_has_module_perms
    for backend in auth.get_backends():
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 40, in get_backends
    return _get_backends(return_tuples=False)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 29, in _get_backends
    backend = load_backend(backend_path)
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 23, in load_backend
    return import_string(path)()
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/module_loading.py", line 28, in import_string
    six.reraise(ImportError, ImportError(msg), sys.exc_info()[2])
  File "/usr/home/self/.virtualenvs/rp/lib/python2.7/site-packages/django/utils/module_loading.py", line 24, in import_string
    return getattr(module, class_name)
ImportError: Module "axes.backends" does not define a "AxesBackend" attribute/class`

**Comment by drozdowsky** [comment]
To be closed. I have used 'latest' doc when I should have used 4.5.4 doc
