### ISSUE TITLE
Support for Django Channels (ASGI)

### ISSUE THREAD

**Issue by Archmonger** [jazzband/django-axes#712]
Currently, Django Axes results in an exception when used with the login functionality within Django-Channels `channels.auth`. 

If multiple backends are defined in `settings.py`, Django Channels requires the user to define a backend to authenticate with. For example,

```python
            await login(
                self.scope,
                self.scope["user"],
                backend="django.contrib.auth.backends.ModelBackend",
            )
```

But when the user defines this backend, it breaks the Axes authentication stack.

```python
ERROR conreq.utils.server_websockets: Websocket failed to connect: Login failure.
Traceback (most recent call last):
  File "C:\Users\Username\Repositories\Conreq\conreq\utils\server_websockets.py", line 32, in connect
    await login(
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\asgiref\sync.py", line 296, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\asyncio\tasks.py", line 455, in wait_for
    return await fut
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\channels\db.py", line 13, in thread_handler
    return super().thread_handler(loop, *args, **kwargs)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\asgiref\sync.py", line 334, in thread_handler
    return func(*args, **kwargs)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\channels\auth.py", line 108, in login
    user_logged_in.send(sender=user.__class__, request=None, user=user)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\django\dispatch\dispatcher.py", line 177, in send
    return [
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\django\dispatch\dispatcher.py", line 178, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\axes\signals.py", line 33, in handle_user_logged_in
    AxesProxyHandler.user_logged_in(*args, **kwargs)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\axes\helpers.py", line 476, in inner
    return func(*args, **kwargs)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\axes\handlers\proxy.py", line 108, in user_logged_in
    return cls.get_implementation().user_logged_in(sender, request, user, **kwargs)
  File "C:\Users\Username\Repositories\Conreq\venv\lib\site-packages\axes\handlers\database.py", line 199, in user_logged_in
    clean_expired_user_attempts(request.axes_attempt_time)
AttributeError: 'NoneType' object has no attribute 'axes_attempt_time'
```

Perhaps it's worth discussing with the Django Channels team whether a workaround can be reached with their `login` function.

**Comment by aleksihakli** [comment]
Hey @Archmonger, thanks for reporting! I think ASGI support would be essential to have as well. This would also be a good target for version 6.0.0.

Since we'd need to define a target setup that should work out-of-the-box or otherwise, would you mind posting example settings that should work with Axes and ASGI enabled?

**Comment by Archmonger** [comment]
This is the GitHub repository that I've been attempting to reach compatibility with [https://github.com/Archmonger/Conreq](https://github.com/Archmonger/Conreq). Repo only has python dependencies. I'll post some settings.py code snippets tomorrow evening.

**Comment by aleksihakli** [comment]
That's good, let's go forward from there.

What other Django packages are you using by the way? It seems like the error is coming from [https://github.com/jazzband/django-axes/blob/master/axes/handlers/proxy.py#L114](here) and the request should just be updated with the `request.axes_attempt_time` attribute. It seems like the request is `None`, where does that come from? Should we have a check for `None` request in [`user_logged_in`](https://github.com/jazzband/django-axes/blob/master/axes/handlers/database.py#L191) similar to e.g. [`user_login_failed`](https://github.com/jazzband/django-axes/blob/master/axes/handlers/database.py#L85) method?

**Comment by Archmonger** [comment]
The none request probably comes from the fact that Django channels refuses to work through multiple authentication backends.
If multiple backends are configured, it will force the user to define only one for every login call.
```python
            await login(
                self.scope,
                self.scope["user"],

                backend="django.contrib.auth.backends.ModelBackend", # <<< This line right here
            )
```
So therefore all the fancy axes request attributes never get populated. Or at least that's my leading theory, I haven't looked at your team's source code.

Here's a list of django requirements I pulled out of my requirements.txt

```python
awesome-django-timezones==0.3.0
channels==3.0.3
diskcache==5.1.0
django==3.1.5
django-htmlmin==0.11.0
django-solo==1.1.5
django-searchable-encrypted-fields==0.1.9
django-cleanup==5.1.0
daphne==3.0.1
django-project-version[git]==0.13.0
pwned-passwords-django==1.4.1
whitenoise[brotli]==5.2.0
```

**Comment by Archmonger** [comment]
Just had a thought. Perhaps the to solution to "only one auth backend can be set" within channels is having the axes backend wrap one or more backends. For example a through a `AXES_AUTH_BACKENDS` variable.

**Comment by aleksihakli** [comment]
@Archmonger wrapping is actually a nice idea, if it can be done cleanly! Would you be interested in inspecting this on the code level? The authentication backend API specification from Django docs would need to be followed and ASGI implementation checked as well.

**Comment by Archmonger** [comment]
Sure. I'll consider a PR on axes as a part of my task list. I have a few higher priority cards so I'll get to it within roughly a month.

**Comment by Archmonger** [comment]
My work schedule slowed down my OSS work. Still aiming to tackle this as a PR but unsure what my timeline looks like.

**Comment by aleksihakli** [comment]
Roger that @Archmonger 👍 No need to worry about timelines since Axes is a voluntary FOSS project.

**Comment by aleksihakli** [comment]
Forcibly setting the backend could lead to hard-to-debug problems in some stacks. Could there be alternatives to this approach or could we e.g. introduce a new flag for configuring another authentication backend separately in Axes that we could then invoke from e.g. a new Axes ASGI authentication wrapper backend?

**Comment by aleksihakli** [comment]
I'd rather have an added configuration key in the settings and think that "explicit is better than implicit" in this case. If we are using ASGI and have upgrade the Axes settings, it might also be feasible to add [system checks](https://github.com/jazzband/django-axes/blob/master/axes/checks.py) in the Django checks framework for making sure that the user has correctly configured the authentication stack i.e. has the `AUTHENTICATION_BACKENDS` and `AXES_AUTHENTICATION_BACKENDS` configured with correct looking types and values.
