### ISSUE TITLE
Axes + POST requests w/lists results in AttributeError in axes.helpers.get

### ISSUE THREAD

**Issue by laumann** [jazzband/django-axes#727]
I'm not entirely sure if this is a bug in django-axes, or we're using it wrong, so I'll outline what I've observed and what I see as a potential problem.

Versions (that I _think_ are relevant):
 - Django==2.2.6
 - django-axes==5.9.0
 - djangorestframework==3.11.0
 - djangorestframework-simplejwt==4.3.0

I implemented a view that supports a POST request to update some data structures, that accepts a list of things as input.

So the request body would be something like `[{…}, {…}]`.

When input data validation, I have a Serializer and did:

```python
class EIPDiscoverView(APIView):
    def post(self, request, id=None):
        obj = DeviceEIPSerializer(data=request.data, many=True)
        obj.is_valid(raise_exception=True)
```
when the input is valid, there no problem, but when the exception is raised, I get an error from `helpers.get_client_username()`

To illustrate the problem, I turned up logging to DEBUG and added 

### A successful request

```
DEBUG:axes.helpers:Using parameter credentials to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.attempts:AXES: Getting all access attempts from database because no AXES_COOLOFF_TIME is configured
DEBUG:axes.helpers:Using parameter request.POST to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:<QueryDict: {'username': ['laumann'], 'password': ['***']}>
DEBUG:axes.helpers:Using parameter credentials to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.attempts:AXES: Getting all access attempts from database because no AXES_COOLOFF_TIME is configured
"POST /api/token/ HTTP/1.1" 200 524
INFO:django.server:"POST /api/token/ HTTP/1.1" 200 524
[{'ip': '192.168.10.3', 'identityObject': {'VendCode': 243, 'ProdType': 2, 'ProdCode': 6153, 'MajRev': 1, 'MinRev': 16, 'ProdName': 'ATV320'}}]
Found 1 devices
DEBUG:axes.helpers:Using parameter request.POST to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:<QueryDict: {}>
DEBUG:axes.helpers:Using parameter credentials to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.attempts:AXES: Getting all access attempts from database because no AXES_COOLOFF_TIME is configured
"POST /api/v1/discover/ethernet-ip/21cd2103-fd23-49c5-8434-2325c3bb4d2e/ HTTP/1.1" 200 25
```

### An error case

```
DEBUG:axes.helpers:Using parameter credentials to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.attempts:AXES: Getting all access attempts from database because no AXES_COOLOFF_TIME is configured
DEBUG:axes.helpers:Using parameter request.POST to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:<QueryDict: {'username': ['laumann'], 'password': ['***']}>
DEBUG:axes.helpers:Using parameter credentials to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.attempts:AXES: Getting all access attempts from database because no AXES_COOLOFF_TIME is configured
"POST /api/token/ HTTP/1.1" 200 524
INFO:django.server:"POST /api/token/ HTTP/1.1" 200 524
[{'ip': '192.168.10.3', 'identityObject': {'VendCode': 243, 'ProdType': 2, 'ProdCode': 6153, 'MajRev': 1, 'MinRev': 16, 'ProdName': 'ATV320'}}]
DEBUG:axes.helpers:Using parameter request.POST to get username with key settings.AXES_USERNAME_FORM_FIELD
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:[{'ip': '192.168.10.3', 'identityObject': {'VendCode': 243, 'ProdType': 2, 'ProdCode': 6153, 'MajRev': 1, 'MinRev': 16, 'ProdName': 'ATV320'}}]
Traceback (most recent call last):
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/axes/middleware.py", line 47, in __call__
    username = get_client_username(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/axes/helpers.py", line 145, in get_client_username
    return request_data.get(settings.AXES_USERNAME_FORM_FIELD, None)
AttributeError: 'list' object has no attribute 'get'
```

There's a bunch of exceptions following this initial exception, but I think this is the root of it.

<details>
<summary>Following errors</summary>
<pre><code>During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 305, in get_traceback_data
    'filtered_POST_items': list(self.filter.get_post_parameters(self.request).items()),
AttributeError: 'list' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 305, in get_traceback_data
    'filtered_POST_items': list(self.filter.get_post_parameters(self.request).items()),
AttributeError: 'list' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/reversion/middleware.py", line 26, in __call__
    return self.get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/reversion/views.py", line 35, in do_revision_view
    response = func(request, *args, **kwargs)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 305, in get_traceback_data
    'filtered_POST_items': list(self.filter.get_post_parameters(self.request).items()),
AttributeError: 'list' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 94, in technical_500_response
    html = reporter.get_traceback_html()
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 333, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
  File "/home/tj/.virtualenvs/omnio3/lib/python3.8/site-packages/django/views/debug.py", line 305, in get_traceback_data
    'filtered_POST_items': list(self.filter.get_post_parameters(self.request).items()),
AttributeError: 'list' object has no attribute 'items'
</code></pre>
</details>

Basically AFAICT it comes down to the lines:

https://github.com/jazzband/django-axes/blob/ea4d3c477dd1fda2045ed8c927b6d0bb87200d27/axes/helpers.py#L141-L142

where it is assumed that `request_data` has a `get()` method. 

In both of the cases above, the first request where we log `request_data` is to obtain a JWT:
```
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:<QueryDict: {'username': ['laumann'], 'password': ['***']}>
```
Where `request_data` then has type `QueryDict`.

When an exception is raised, `request_data` appears to be whatever was submitted in the request, ie in my case a list.

```
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:[{'ip': '192.168.10.3', 'identityObject': {'VendCode': 243, 'ProdType': 2, 'ProdCode': 6153, 'MajRev': 1, 'MinRev': 16, 'ProdName': 'ATV320'}}]
```
whereas in the successful case, the type is still a `QueryDict` (that is empty)
```
DEBUG:axes.helpers:Here's our request_data...
DEBUG:axes.helpers:<QueryDict: {}>
```

### Workarounds

I've considered two workarounds:

 - Use the customization option to provide my own [username lookup](https://django-axes.readthedocs.io/en/latest/5_customization.html#customizing-username-lookups), where I could then check if the input is a list and return `None` in that case, and set `AXES_USERNAME_CALLABLE`.
 - Make sure that whatever is received in `get_client_username()` actually has a `get()` function

I've gone with the latter, and just defined a top-level object, like:

```json
{
    "eipDevices": [{"ip": "192.168.10.3", "identityObject": {"VendCode": 243, "ProdType": 2, "ProdCode": 6153, "MajRev": 1, "MinRev": 16, "ProdName": "ATV320"}}]
}
```

This makes it so even in the event of an exception the `request_data.get(…)` line doesn't fail with AttributeError and the expected error return code is received.

### Questions

 - Is this a bug in django-axes? I'm happy to implement and submit a PR with a fix
 - Am I doing something wrong in my usage of django-axes?

Sorry for the long-winded post, but it's hard to know what can be left out when I basically am unsure of where the problem is and what interaction is causing what errors.

**Comment by aleksihakli** [comment]
Thanks for the detailed issue @laumann!

Seems like this is a problem with the request data being a `list` instead of `dict`.

You are using an outdated version of Axes which fetches user attributes in the middleware which results in your error. Could you try updating Axes to the latest version which is currently `django-axes==5.13.1`?

**Comment by laumann** [comment]
> Thanks for the detailed issue @laumann!

No problem :smile: 
 
> Seems like this is a problem with the request data being a `list` instead of `dict` and the you seem to be using an older version `5.9.0` of Axes which fetches user attributes in the middleware which results in your error with the combination of input data typing. We removed that logic from the middleware in `5.10.0`.
> 
> Could you try updating Axes to the latest version which is currently `django-axes==5.13.1` and see if that fixes your problem?

Ah sure, I'll try it out. I figured that since the code was the same in `get_client_username()` the behaviour would be the same, so I didn't try the update. Thanks for the explanation.

**Comment by aleksihakli** [comment]
The difference is that `get_client_username()` is not invoked in the middleware in the recent versions: it is only invoked on authentication attempts and lockout signal resolution instead of every request that goes through the middleware.
