### ISSUE TITLE
get_ip dependency on django.utils.six

### ISSUE THREAD

**Issue by edward-springload** [jazzband/django-axes#822]
Under Python 3.9.9 and Django 3.2.1:

Traceback (most recent call last):
  File "/app/manage.py", line 8, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    django.setup()
  File "/usr/local/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.9/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/usr/local/lib/python3.9/site-packages/axes/apps.py", line 11, in ready
    from axes import signals    # we must load signals
  File "/usr/local/lib/python3.9/site-packages/axes/signals.py", line 13, in <module>
    from axes.attempts import get_cache_key
  File "/usr/local/lib/python3.9/site-packages/axes/attempts.py", line 10, in <module>
    from axes.utils import get_ip
  File "/usr/local/lib/python3.9/site-packages/axes/utils.py", line 4, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/local/lib/python3.9/site-packages/django/utils/__init__.py)

**Comment by edward-springload** [comment]
Need coffee sorry
