### ISSUE TITLE
ValueError: 'AccessFailureLog' is not in list after update to 5.32 from 5.31

### ISSUE THREAD

**Issue by kwint** [jazzband/django-axes#874]
Hi, 

I'm experiencing an issue when opening django admin after updating axes to 5.32 from 5.31. I don't see anything in the changelog that would explain this issue.

Full log:
```
2022-04-21 11:03:58 [ERROR] Internal Server Error: /mxadmin/
Traceback (most recent call last):
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/asgiref/sync.py", line 451, in thread_handler
    raise exc_info[1]
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/core/handlers/exception.py", line 38, in inner
    response = await get_response(request)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/core/handlers/base.py", line 263, in _get_response_async
    response = await sync_to_async(response.render, thread_sensitive=True)()
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/asgiref/sync.py", line 414, in __call__
    ret = await asyncio.wait_for(future, timeout=None)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/asgiref/current_thread_executor.py", line 22, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/asgiref/sync.py", line 455, in thread_handler
    return func(*args, **kwargs)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/sentry_sdk/integrations/django/templates.py", line 73, in rendered_content
    return real_rendered_content.fget(self)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/response.py", line 83, in rendered_content
    return template.render(context, self._request)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/loader_tags.py", line 195, in render
    return template.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 172, in render
    return self._render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/test/utils.py", line 100, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/home/quint/.cache/pypoetry/virtualenvs/metal-cloud-jSwC9-qh-py3.10/lib/python3.10/site-packages/django/template/defaulttags.py", line 170, in render
    values = list(values)
  File "/home/quint/code/metal-cloud/server/settings/components/common.py", line 283, in get_app_list
    app["models"].sort(key=lambda x: object_list.index(x["object_name"]))
  File "/home/quint/code/metal-cloud/server/settings/components/common.py", line 283, in <lambda>
    app["models"].sort(key=lambda x: object_list.index(x["object_name"]))
ValueError: 'AccessFailureLog' is not in list
```

On django 3.2.13 with python 3.10

I see in https://github.com/jazzband/django-axes/blob/master/axes/admin.py that there is an `AccessFailureLog` registered. If I add this to the `ADMIN_ORDERING` setting I still get the same error.

Snippet from `common.py` settings:
```
# Django admin
ADMIN_ORDERING = [
    ("runner", ["CoreRun", "ToolpathChunk"]),
    ("libraries", ["Material"]),
    ("licensing", ["UserLicense"]),
    ("auth", ["User", "Group"]),
    ("authtoken", ["TokenProxy"]),
    ("axes", ["AccessAttempt", "AccessLog"]),  # I have tried adding AccessFailureLog here
]


def get_app_list(self, request):
    app_dict = self._build_app_dict(request)
    for app_name, object_list in ADMIN_ORDERING:
        app = app_dict[app_name]
        app["models"].sort(key=lambda x: object_list.index(x["object_name"]))
        yield app
```

**Comment by hramezani** [comment]
I've tested your snippet and it worked for me by adding `AccessFailureLog`.

```python
from django.contrib.admin import AdminSite


ADMIN_ORDERING = [
    ("auth", ["User", "Group"]),
    ("axes", ["AccessAttempt", "AccessLog", "AccessFailureLog"]),  # I have tried adding AccessFailureLog here
]


class MyAdminSite(AdminSite):
    def get_app_list(self, request):
        app_dict = self._build_app_dict(request)
        for app_name, object_list in ADMIN_ORDERING:
            app = app_dict[app_name]
            print(app)
            app["models"].sort(key=lambda x: object_list.index(x["object_name"]))
            yield app

```

**Comment by aleksihakli** [comment]
Hi @kwint and thanks for reporting. Did you have success fixing this yet?

**Comment by kwint** [comment]
I was just having another shot at this. But indeed adding `"AccessFailureLog"` to the `ADMIN ORDERING` list works now. I might have screwed something up when I did this before.
